apiVersion: ipmonitor/dev
kind: Deployment
metadata:
  name: ipmonitor
  labels:
    app: ipmonitor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ipmonitor
  template:
    metadata:
      labels:
        app: ipmonitor
    spec:
      containers:
      - name: ipmonitor
        image: ipmonitor.azurecr.io:dev
        ports:
        - containerPort: 8080
