apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipmonitor
  labels:
    app: ipmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipmonitor
  template:
    metadata:
      labels:
        app: ipmonitor
    spec:
      containers:
      - name: ipmonitor
        image: ipmonitor.azurecr.io/ipmonitor:dev
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: ipmonitor
spec:
  type: LoadBalancer
  selector:
    app: ipmonitor
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
