apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipmonitor
  labels:
    app: ipmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipmonitor
  template:
    metadata:
      labels:
        app: ipmonitor
    metadata:
  name: ipmonitor
  labels:
    app: ipmonitor
      containers:
      - name: ipmonitor
        image: ipmonitor.azurecr.io:dev
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service	
metadata:
  name: ipmonitor
spec:
	ports:
	- port: 8080
	selector:
	app: ipmonitor
  
