apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ipmon-deployment
  name: ipmon-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: ipmon-deployment
  type: NodePort
status:
  loadBalancer: {}
