apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: ipmon-deployment
  name: ipmon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ipmon-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ipmon-deployment
    spec:
      containers:
      - args:
        - –replicas=3
        image: polganesh/ipmon:dev
        name: ipmon-deployment
        ports:
        - containerPort: 8080
        resources: {}
status: {}
